=== dval-in/dvalin-data/schemas/AchievementCategory.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "achievements": {
      "items": {
        "properties": {
          "desc": {
            "type": "string"
          },
          "hidden": {
            "type": "boolean"
          },
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "order": {
            "type": "number"
          },
          "reward": {
            "type": "number"
          }
        },
        "required": [
          "desc",
          "hidden",
          "id",
          "name",
          "order",
          "reward"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "order": {
      "type": "number"
    },
    "_id": {
      "type": "number"
    }
  },
  "required": [
    "achievements",
    "id",
    "name",
    "order",
    "_id"
  ],
  "type": "object",
  "additionalProperties": false
}

=== dval-in/dvalin-data/data/KO/AchievementCategory/MortalTravailsSeries2.json
{
  "_id": 22,
  "id": "MortalTravailsSeries2",
  "name": "속세 순유·제2집",
  "order": 4,
  "achievements": [
    {
      "id": 80069,
      "name": "빛나는 뇌전",
      "desc": "「번개」 원소의 힘 터득하기",
      "reward": 5,
      "hidden": false,
      "order": 69,
      "version": "2.0"
    },
    {
      "id": 80070,
      "name": "민들레의 고향",
      "desc": "《민들레밭의 여우》 전집 모으기",
      "reward": 5,
      "hidden": false,
      "order": 70,
      "version": "2.0"
    },
    {
      "id": 80071,
      "name": "우정과 희생의 가치",
      "desc": "《멧돼지 공주》 전집 모으기",
      "reward": 5,
      "hidden": false,
      "order": 71,
      "version": "2.0"
    },
    {
      "id": 80072,
      "name": "주야의 영원한 청춘",
      "desc": "《소녀 베라의 우울》 전집 모으기",
      "reward": 5,
      "hidden": false,
      "order": 72,
      "version": "2.0"
    },
    {
      "id": 80073,
      "name": "츄츄학의 확장",
      "desc": "《츄츄족 풍습 고찰》 전집 모으기",
      "reward": 5,
      "hidden": false,
      "order": 73,
      "version": "2.0"
    }
  ]
}
