=== dval-in/dvalin-data/schemas/Artifact.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Artifact",
  "definitions": {
    "Artifact": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "minRarity": {
          "type": "number"
        },
        "maxRarity": {
          "type": "number"
        },
        "flower": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ],
          "additionalProperties": false
        },
        "plume": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ],
          "additionalProperties": false
        },
        "sands": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ],
          "additionalProperties": false
        },
        "goblet": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ],
          "additionalProperties": false
        },
        "circlet": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ],
          "additionalProperties": false
        },
        "onePiece": {
          "type": "string"
        },
        "twoPiece": {
          "type": "string"
        },
        "fourPiece": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "minRarity",
        "maxRarity"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/IT/Artifact/ThunderingFury.json
{
  "id": "ThunderingFury",
  "name": "Furia tonante",
  "minRarity": 4,
  "maxRarity": 5,
  "twoPiece": "Bonus DAN da Electro +15%.",
  "fourPiece": "Aumenta di un 40% i DAN da Sovraccarico, Electrocarica, Superconduzione e Iperfioritura. Il bonus DAN conferito da Accentuazione aumenta di un 20%. Innescare una Vivificazione o una delle reazioni elementali di cui sopra riduce il TdR dell'abilità elementale di 1 s. Si può verificare una sola volta ogni 0,8 s.",
  "goblet": {
    
    "id": "OmenOfThunderstorm",
    "name": "Presagio di tempesta",
    "description": "Un calice che contiene il sangue degli innocenti. Trabocca della furia tonante delle preghiere che riecheggiano al suo interno."
  },
  "plume": {
    
    "id": "SurvivorOfCatastrophe",
    "name": "Superstite della catastrofe",
    "description": "Una piuma satura di scariche elettriche che sprigiona ancora l'ira dell'Uccello del tuono."
  },
  "circlet": {
    
    "id": "ThunderSummonersCrown",
    "name": "Corona dell'invocatore di fulmini",
    "description": "Una corona indossata da un antico sciamano che venerava l'Uccello del tuono. La capricciosa bestia rimase indifferente alla devozione che le veniva mostrata."
  },
  "flower": {
    
    "id": "ThunderbirdsMercy",
    "name": "Compassione dell'Uccello del tuono",
    "description": "Un fiore intriso di fulmini, riuscito in qualche modo a sopravvivere alla furia del fuoco purpureo. È l'unico superstite del giorno del disastro."
  },
  "sands": {
    
    "id": "HourglassOfThunder",
    "name": "Clessidra tonante",
    "description": "La clessidra usata per preannunciare l'arrivo dell'Uccello del tuono dalla tribù che lo venerava. Ora che la tribù ha smesso di esistere, è caduta nell'oblio."
  }
}
