=== dval-in/dvalin-data/schemas/Bait.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Bait",
  "definitions": {
    "Bait": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        },
        "craft": {
          "type": "object",
          "properties": {
            "items": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  }
                },
                "required": [
                  "id",
                  "name",
                  "amount"
                ],
                "additionalProperties": false
              }
            },
            "result": {
              "type": "number"
            },
            "version": {
              "type": "string"
            }
          },
          "required": [
            "items",
            "result"
          ],
          "additionalProperties": false
        },
        "fish": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "rarity": {
                "type": "number"
              }
            },
            "required": [
              "id",
              "name",
              "rarity"
            ],
            "additionalProperties": false
          }
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "rarity",
        "craft",
        "fish"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/ZH-T/Bait/FruitPasteBait.json
{
  "id": "FruitPasteBait",
  "name": "果釀餌",
  "description": "十分常見的魚餌，由日落果與小麥搗碎發酵揉製而成，入水後能夠快速霧化，對小型魚類有著強烈的吸引力。由於其製作簡單、價格低廉、效用優秀，因此又被戲稱為「釣魚佬寶珠」。<br/><br/>適用魚種：鱂魚類。",
  "rarity": 2,
  "craft": {
    "items": [
      {
        
        "id": "Sunsettia",
        "name": "日落果",
        "amount": 1
      },
      {
        
        "id": "Wheat",
        "name": "小麥",
        "amount": 1
      }
    ],
    "result": 10
  },
  "fish": [
    {
      
      "id": "AizenMedaka",
      "name": "藍染花鱂",
      "rarity": 3
    },
    {
      
      "id": "Crystalfish",
      "name": "水晶宴",
      "rarity": 3
    },
    {
      
      "id": "Dawncatcher",
      "name": "擒霞客",
      "rarity": 3
    },
    {
      
      "id": "GlazeMedaka",
      "name": "琉璃花鱂",
      "rarity": 3
    },
    {
      
      "id": "Medaka",
      "name": "花鱂",
      "rarity": 3
    },
    {
      
      "id": "SweetflowerMedaka",
      "name": "甜甜花鱂",
      "rarity": 3
    }
  ]
}

=== dval-in/dvalin-data/data/VI/Bait/FakeFlyBait.json
{
	"id": "FakeFlyBait",
	"name": "Mồi Ruồi Giả",
	"description": "Mồi câu mô phỏng theo hình thù ruồi nhặng, được làm từ các nguyên liệu có màu sắc sặc sỡ, không mùi, là mồi câu đặc biệt dành cho các loại cá lớn có thị giác linh hoạt, thông thường sẽ phối hợp với cách câu cá tương đối khó hơn. Hội Câu Cá ở một số nơi còn dùng Mồi Ruồi Giả để làm một trong các tiêu chuẩn tăng cấp cán bộ.Loại cá thích hợp: Cá Rồng, Cá Pháo, Cá Đuối.",
	"rarity": 2,
	"craft": {
		"items": [
			{
				"id": "SakuraBloom",
				"name": "Tú Cầu Anh Đào",
				"amount": 1
			},
			{
				"id": "Horsetail",
				"name": "Đuôi Ngựa",
				"amount": 1
			}
		],
		"result": 10
	},
	"fish": [
		{
			"id": "BitterPufferfish",
			"name": "Cá Pháo Cay Đắng",
			"rarity": 3
		},
		{
			"id": "GoldenKoi",
			"name": "Cá Rồng Xích Kim",
			"rarity": 3
		},
		{
			"id": "Pufferfish",
			"name": "Cá Pháo",
			"rarity": 3
		},
		{
			"id": "RustyKoi",
			"name": "Cá Rồng Thép",
			"rarity": 3
		},
		{
			"id": "DivdaRay",
			"name": "Cá Đuối Divda",
			"rarity": 3
		},
		{
			"id": "FormaloRay",
			"name": "Cá Đuối Formalo",
			"rarity": 3
		}
	]
}
