=== dval-in/dvalin-data/schemas/CommonMaterial.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"craft": {
			"properties": {
				"cost": {
					"type": "number"
				},
				"items": {
					"items": {
						"properties": {
							"amount": {
								"type": "number"
							},
							"id": {
								"type": "string"
							},
							"name": {
								"type": "string"
							}
						},
						"required": ["amount", "id", "name"],
						"type": "object"
					},
					"type": "array"
				}
			},
			"required": ["cost", "items"],
			"type": "object"
		},
		"description": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"rarity": {
			"type": "number"
		},
		"source": {
			"items": {
				"type": "string"
			},
			"type": "array"
		},
		"version": {
			"type": "string"
		}
	},
	"required": ["description", "id", "name", "rarity", "source", "version"],
	"type": "object",
	"additionalProperties": false
}

=== dval-in/dvalin-data/data/VI/WeaponSecondaryMaterial/RobustFungalNucleus.json
{
  "id": "RobustFungalNucleus",
  "name": "Nhân Bào Nấm Hồi Phục",
  "description": "Người ta thường tin rằng Nấm Quỷ phát triển khả năng di chuyển là để phân tán bào tử trong thế giới rộng lớn hơn. Một nhà thơ đã từng nói rằng trong giấc mơ chung của Nấm Quỷ, bào tử bao phủ núi non và đại dương, và thế giới vô cùng yên bình. Nấm Quỷ tiến hóa thành cá, thú, chim chóc, con người và thần linh. Chúng sinh trưởng dựa vào lượng mưa, đất đai và đồng loại của chúng khi trở về đất mẹ.",
  "source": [
    "Ghép Nhận",
    "Nấm Quỷ cấp 60 trở lên trong trạng thái Bung Nở rơi",
    "Nấm Quỷ cấp 60 trở lên trong trạng thái Khô Héo rơi"
  ],
  "rarity": 4,
  "craft": {
    "cost": 125,
    "items": [
      {
        "id": "DormantFungalNucleus",
        "name": "Nhân Bào Nấm Bất Động",
        "amount": 3
      }
    ]
  },
  "version": "3.0"
}
