=== dval-in/dvalin-data/schemas/CommonMaterial.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"craft": {
			"properties": {
				"cost": {
					"type": "number"
				},
				"items": {
					"items": {
						"properties": {
							"amount": {
								"type": "number"
							},
							"id": {
								"type": "string"
							},
							"name": {
								"type": "string"
							}
						},
						"required": ["amount", "id", "name"],
						"type": "object"
					},
					"type": "array"
				}
			},
			"required": ["cost", "items"],
			"type": "object"
		},
		"description": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"rarity": {
			"type": "number"
		},
		"source": {
			"items": {
				"type": "string"
			},
			"type": "array"
		},
		"version": {
			"type": "string"
		}
	},
	"required": ["description", "id", "name", "rarity", "source", "version"],
	"type": "object",
	"additionalProperties": false
}

=== dval-in/dvalin-data/data/FR/WeaponPrimaryMaterial/BlazingSacrificialHeartsHesitance.json
{
  "id": "BlazingSacrificialHeartsHesitance",
  "name": "Hésitation du cœur sacrificiel flamboyant",
  "description": "Alors que les civilisations originelles s'effondraient comme du jade brisé, et que les créatures célestes, sous la conduite desquelles les civilisations terrestres avaient prospéré, étaient dévorées par les dragons éveillés, l'humanité s'enfonça dans la sauvagerie, perdant la capacité de percevoir le monde d'une manière nouvelle. C'est ainsi qu'ils revinrent à leurs croyances les plus primitives, convaincus du mystère inhérent à la terre qui nourrissait toutes choses. Cela marqua l'aube de l'ère où les proies chassées commencèrent à être offertes en sacrifice.",
  "source": [
    "Synthèse"
  ],
  "rarity": 3,
  "craft": {
    "cost": 125,
    "items": [
      {
        "id": "BlazingSacrificialHeartsTerror",
        "name": "Terreur du cœur sacrificiel flamboyant",
        "amount": 3
      }
    ]
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/ES/CommonMaterial/GoldenRavenInsignia.json
{
  "id": "GoldenRavenInsignia",
  "name": "Insignia de cuervo dorada",
  "description": "Una insignia de cuervo que simboliza el orgullo y los principios por los que se rigen los Ladrones de Tesoros. Ya sea ocultos en las profundidades de la tierra o en el insondable fondo del mar, mientras haya tesoros que cazar, el inmortal espíritu de los Ladrones de Tesoros no se detendrá ante nada para obtenerlos.",
  "source": [
    "Sintetizar",
    "Obtenido de Ladrones de Tesoros (Niv. 60+)",
    "Sintetizar",
    "Obtenido de Ladrones de Tesoros (Niv. 60+)"
  ],
  "rarity": 3,
  "craft": {
    "cost": 50,
    "items": [
      {
        "id": "SilverRavenInsignia",
        "name": "Insignia de cuervo plateada",
        "amount": 3
      },
      {
        "id": "SilverRavenInsignia",
        "name": "Insignia de cuervo plateada",
        "amount": 3
      }
    ]
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/RU/CommonMaterial/TransoceanicChunk.json
{
  "id": "TransoceanicChunk",
  "name": "Обломок из иноморья",
  "description": "Легенды рассказывают о великих существах, которые живут в далёких морях, где не проходят морские пути и куда не ступает нога человека, но ни одно обычное море не может похвастаться жизненными силами моря Фонтейна.",
  "source": [
    "Алхимия",
    "Инороды Фонтмера Ур. 40+",
    "Звёздная пыль"
  ],
  "rarity": 2,
  "craft": {
    "cost": 25,
    "items": [
      {
        "id": "TransoceanicPearl",
        "name": "Жемчужина иноморья",
        "amount": 3
      }
    ]
  },
  "version": "4.0"
}

=== dval-in/dvalin-data/data/DE/WeaponSecondaryMaterial/BlackCrystalHorn.json
{
  "id": "BlackCrystalHorn",
  "name": "Schwarzes Kristallhorn",
  "description": "Ein leuchtendes Metallhorn, versehen mit unbekannten dunklen Kristallverzierungen. Es scheint kaum benutzt worden zu sein und muss wohl f√ºr wichtige Hilichurl-Rituale vorgesehen sein.",
  "source": [
    "Kann hergestellt werden",
    "Beute von Mitachurlen ab Stufe 60",
    "Beute von Lawachurlen ab Stufe 60"
  ],
  "rarity": 4,
  "craft": {
    "cost": 125,
    "items": [
      {
        "id": "BlackBronzeHorn",
        "name": "Kupferhorn",
        "amount": 3
      }
    ]
  },
  "version": "1.6"
}

=== dval-in/dvalin-data/data/FR/CommonMaterial/SpectralHeart.json
{
  "id": "SpectralHeart",
  "name": "Cœur spectral",
  "description": "Ces formes de vie élémentaires ont des habitudes de comportement étranges et augmenteront périodiquement leur nombre avant de disparaître.",
  "source": [
    "Synthèse",
    "Butin de Spectre (Niv.40+)",
    "Échange Astrions"
  ],
  "rarity": 2,
  "craft": {
    "cost": 25,
    "items": [
      {
        "id": "SpectralHusk",
        "name": "Coquille spectrale",
        "amount": 3
      }
    ]
  },
  "version": "2.1"
}

=== dval-in/dvalin-data/data/IT/CommonMaterial/TrimmedRedSilk.json
{
  "id": "TrimmedRedSilk",
  "name": "Seta rossa ritagliata",
  "description": "Un guerriero esperto può intuire la debolezza dagli occhi del proprio avversario e trarne vantaggio. Da tempo, gli Eremiti hanno perso un padrone da servire, e ora non hanno più nessuno di cui fidarsi. Si dice che siano fermamente convinti che il tradimento si nasconda dietro ogni cosa, persino dietro ai loro stessi occhi.",
  "source": [
    "Creato",
    "Ottenibile dagli Eremiti di liv. 40+",
    "Scambio di Polvere stellare",
    "Creato",
    "Ottenibile dagli Eremiti di liv. 40+",
    "Scambio di Polvere stellare"
  ],
  "rarity": 2,
  "craft": {
    "cost": 25,
    "items": [
      {
        "id": "FadedRedSatin",
        "name": "Seta rossa sbiadita",
        "amount": 3
      },
      {
        "id": "FadedRedSatin",
        "name": "Seta rossa sbiadita",
        "amount": 3
      }
    ]
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/RU/WeaponSecondaryMaterial/ConcealedUnguis.json
{
  "id": "ConcealedUnguis",
  "name": "Скрытый заточенный коготь",
  "description": "Они очень любопытны, но с Дурином, шедевром гумусового слоя, эти псы элювиального слоя не идут ни в какое сравнение.",
  "source": [
    "Алхимия",
    "Волки Разрыва Ур. 40+",
    "Покупается за Звёздную пыль",
    "Алхимия",
    "Волки Разрыва Ур. 40+",
    "Покупается за Звёздную пыль"
  ],
  "rarity": 3,
  "craft": {
    "cost": 50,
    "items": [
      {
        "id": "ConcealedClaw",
        "name": "Скрытый коготь",
        "amount": 3
      },
      {
        "id": "ConcealedClaw",
        "name": "Скрытый коготь",
        "amount": 3
      }
    ]
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/KO/WeaponSecondaryMaterial/ForeignSynapse.json
{
  "id": "ForeignSynapse",
  "name": "이세계의 시냅스",
  "description": "이런 특이한 생명체의 근원은 엘리나스이며, 활동 범위 역시 엘리나스를 중심으로 돌아간다",
  "source": [
    "합성 획득",
    "Lv.40 이상 균열계 원형체 드랍",
    "스타더스트 교환"
  ],
  "rarity": 3,
  "craft": {
    "cost": 50,
    "items": [
      {
        "id": "RiftCore",
        "name": "균열의 코어",
        "amount": 3
      }
    ]
  },
  "version": "4.0"
}
