=== dval-in/dvalin-data/schemas/ElementalStoneMaterial.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ElementalStoneMaterial",
  "definitions": {
    "ElementalStoneMaterial": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "source": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "rarity": {
          "type": "number"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "source",
        "rarity",
        "version"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/VI/ElementalStoneMaterial/EverflameSeed.json
{
  "id": "EverflameSeed",
  "name": "Ngọn Lửa Vĩnh Hằng",
  "description": "Dòng chảy năng lượng lưu chuyển sâu trong đại địa mang theo nguyện vọng vô tận, nương theo ngọn lửa thấm vào thực vật, khiến nó lúc nào cũng cháy rực và khao khát dùng hoa lửa tẩy sạch mọi thứ, đây là thứ nguyện vọng gì nhỉ.",
  "source": [
    "Cây Nổ cấp 30 trở lên rơi"
  ],
  "rarity": 4,
  "version": "5.0"
}

=== dval-in/dvalin-data/data/IT/ElementalStoneMaterial/ArtificedSpareClockworkComponentCoppelia.json
{
  "id": "ArtificedSpareClockworkComponentCoppelia",
  "name": "Componente meccanico di ricambio artificiale (Coppelia)",
  "description": "Secondo il progetto del suo creatore, la storia della Danzautoma dalle delicate giunture termina con un lieto fine. Su chiunque tenterà di disturbare quell'istante, Coppelia scaglierà sventura grazie alle sue impressionanti abilità di combattimento.",
  "source": [
    "Ottenibile da Suite del Vento glaciale di liv. 30+",
    "Ottenibile da Suite del Vento glaciale di liv. 30+"
  ],
  "rarity": 4,
  "version": "5.0"
}

=== dval-in/dvalin-data/data/EN/WeaponSecondaryMaterial/ChaosStorage.json
{
  "id": "ChaosStorage",
  "name": "Chaos Storage",
  "description": "Ruin Drakes can absorb Elemental Energy from the outside and store it in this component inside their \"neck.\"",
  "source": [
    "Dropped by Ruin Drakes",
    "Stardust Exchange",
    "Dropped by Ruin Drakes",
    "Stardust Exchange"
  ],
  "rarity": 2,
  "version": "5.0"
}
