=== dval-in/dvalin-data/schemas/Fish.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "bait": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "name",
        "rarity"
      ],
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "rarity": {
      "type": "number"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "bait",
    "description",
    "id",
    "name",
    "rarity",
    "source",
    "version"
  ],
  "type": "object",
  "additionalProperties": false
}

=== dval-in/dvalin-data/data/TR/Fish/TrueFruitAngler.json
{
  "id": "TrueFruitAngler",
  "name": "Gerçek Meyve Balığı",
  "description": "Su altında yuva kazmak, barınak yapmak ve yırtıcıları uzaklaştırmak için boynuz benzeri kıkırdaklı bir yapıya sahip olan orta büyüklükte ve yuvarlak bir balık.<br/>Bu tür balon balıkları genelde yeşilimsi bir tona sahip olurlar. Görünümleri olgunlaşmamış bir meyveye benzediğinden ötürü \"Gerçek Meyve\" ismini almıştır. Eti oldukça yağlı ve besleyicidir ama usulüne göre işlenmezse veya safra kesesi geç çıkarılırsa tadı olgunlaşmamış bir meyve gibi ekşi olur. Bundan ötürü \"bu balığı lezzetli yapmak\" tüm şeflerin ölçüldüğü standart haline gelmiştir.",
  "rarity": 3,
  "source": [
    "Balık tutarak elde edilir."
  ],
  "bait": {
    "id": "SugardewBait",
    "name": "Şeker Özü Yemi",
    "rarity": 2
  },
  "version": "5.0"
}
