=== dval-in/dvalin-data/schemas/Food.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"description": {
			"type": "string"
		},
		"dishType": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"ingredients": {
			"items": {
				"properties": {
					"amount": {
						"type": "number"
					},
					"id": {
						"type": "string"
					},
					"name": {
						"type": "string"
					}
				},
				"required": ["amount", "id", "name"],
				"type": "object"
			},
			"type": "array"
		},
		"name": {
			"type": "string"
		},
		"rarity": {
			"type": "number"
		},
		"results": {
			"properties": {
				"delicious": {
					"properties": {
						"description": {
							"type": "string"
						},
						"effect": {
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": ["description", "effect", "name"],
					"type": "object"
				},
				"normal": {
					"properties": {
						"description": {
							"type": "string"
						},
						"effect": {
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": ["description", "effect", "name"],
					"type": "object"
				},
				"special": {
					"properties": {
						"character": {
							"properties": {
								"id": {
									"type": "string"
								},
								"name": {
									"type": "string"
								}
							},
							"required": ["id", "name"],
							"type": "object"
						},
						"description": {
							"type": "string"
						},
						"effect": {
							"type": "string"
						},
						"id": {
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": ["character", "description", "effect", "id", "name"],
					"type": "object"
				},
				"suspicious": {
					"properties": {
						"description": {
							"type": "string"
						},
						"effect": {
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": ["description", "effect", "name"],
					"type": "object"
				}
			},
			"required": ["delicious", "normal", "suspicious"],
			"type": "object"
		},
		"version": {
			"type": "string"
		}
	},
	"required": [
		"description",
		"dishType",
		"id",
		"ingredients",
		"name",
		"rarity",
		"results",
		"version"
	],
	"type": "object",
	"additionalProperties": false
}

=== dval-in/dvalin-data/data/TH/Food/FontainianFoieGras.json
{
  "id": "FontainianFoieGras",
  "name": "Fontainian Foie Gras",
  "description": "อาหารต้นตำรับของ Fontaine เพียงแค่นำฟัวกราส์มาย่างก็สามารถนำไปเสิร์ฟบนจานได้ ผิวข้างนอกเป็นสีน้ำตาลอ่อน เนื้อข้างในนุ่มละมุนลิ้น ความอร่อยที่ได้มาจากการควบคุมไฟในการย่างอย่างแม่นยำ ตอนทำต้องใช้สมาธิ และความตั้งใจ เพราะถ้าไม่ระวังฟัวกราส์อาจจะกลายเป็นก้อนน้ำมันก็ได้",
  "rarity": 3,
  "ingredients": [
    {
      "id": "Fowl",
      "name": "Fowl",
      "amount": 2
    },
    {
      "id": "Jam",
      "name": "Jam",
      "amount": 1
    },
    {
      "id": "Marcotte",
      "name": "Marcotte",
      "amount": 1
    },
    {
      "id": "Fowl",
      "name": "Fowl",
      "amount": 2
    },
    {
      "id": "Jam",
      "name": "Jam",
      "amount": 1
    },
    {
      "id": "Marcotte",
      "name": "Marcotte",
      "amount": 1
    }
  ],
  "dishType": "เมนูการป้องกัน",
  "results": {
    "suspicious": {
      "name": "Fontainian Foie Gras รสประหลาด",
      "description": "อาหารต้นตำรับของ Fontaine เมื่อกัดคำแรกเข้าไป รสชาติอย่างกับได้กินน้ำมันช้อนหนึ่ง เมื่อลองคำที่สองอย่างไม่ตายใจ กลับรู้สึกได้เพียงความเลี่ยนจนยากจะกระเดือกลง... ระ..หรือว่าจะใส่น้ำมันมากเกินไปงั้นเรอะ?",
      "effect": "เพิ่มพลังป้องกันให้กับ สมาชิกทีมทั้งหมดขึ้น 165 หน่วย เป็นเวลา 300 วินาที เมื่อเล่นในโหมดเล่นหลายคน จะมีผลกับตัวละครของตัวเองเท่านั้น"
    },
    "normal": {
      "name": "Fontainian Foie Gras",
      "description": "อาหารต้นตำรับของ Fontaine เพียงแค่นำฟัวกราส์มาย่างก็สามารถนำไปเสิร์ฟบนจานได้ ผิวข้างนอกเป็นสีน้ำตาลอ่อน เนื้อข้างในนุ่มละมุนลิ้น ความอร่อยที่ได้มาจากการควบคุมไฟในการย่างอย่างแม่นยำ ตอนทำต้องใช้สมาธิ และความตั้งใจ เพราะถ้าไม่ระวังฟัวกราส์อาจจะกลายเป็นก้อนน้ำมันก็ได้",
      "effect": "เพิ่มพลังป้องกันให้กับ สมาชิกทีมทั้งหมดขึ้น 200 หน่วย เป็นเวลา 300 วินาที เมื่อเล่นในโหมดเล่นหลายคน จะมีผลกับตัวละครของตัวเองเท่านั้น"
    },
    "delicious": {
      "name": "Fontainian Foie Gras แสนอร่อย",
      "description": "อาหารต้นตำรับของ Fontaine ตับชิ้นอ้วนเนื้อละเอียดละมุนลิ้น ราวกับริบบิ้นนุ่มลื่น เพียงแค่แตะที่ปลายลิ้นแผ่วเบาก็ไหลสู่ลำคอซะแล้ว รสโอชาอันอิ่มเอิบเช่นนี้ อาจทำให้ไร้รสอื่นเทียบเทียมมันได้อีก แต่หากไม่กินก็คงจะเสียดายไปตลอดทั้งชีวิต",
      "effect": "เพิ่มพลังป้องกันให้กับ สมาชิกทีมทั้งหมดขึ้น 235 หน่วย เป็นเวลา 300 วินาที เมื่อเล่นในโหมดเล่นหลายคน จะมีผลกับตัวละครของตัวเองเท่านั้น"
    }
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/ID/Food/GrilledFishInMintSauce.json
{
  "id": "GrilledFishInMintSauce",
  "name": "Grilled Fish in Mint Sauce",
  "description": "Ikan panggang berbalut saus yang nikmat. Ikannya diisi dengan berbagai rempah, lalu dipanggang. Setelah dipanggang, langsung dibaluri oleh saus mint yang banyak. Sehingga aroma ikannya cukup untuk memikat selera makan siapa saja.",
  "rarity": 1,
  "ingredients": [
    {
      "id": "Fish",
      "name": "Fish",
      "amount": 1
    },
    {
      "id": "Mint",
      "name": "Mint",
      "amount": 1
    }
  ],
  "results": {
    "suspicious": {
      "name": "Suspicious Grilled Fish in Mint Sauce",
      "description": "Ikan panggang berbalut saus yang nikmat. Kuahnya yang kental menutupi rasa asli ikannya, dan aroma mint di mulut membuat penikmatnya lupa kalau ini sebenarnya adalah ikan panggang ....",
      "effect": "Memulihkan 8% Max HP dan tambahan 800 HP untuk Karakter yang dipilih."
    },
    "normal": {
      "name": "Grilled Fish in Mint Sauce",
      "description": "Ikan panggang berbalut saus yang nikmat. Ikannya diisi dengan berbagai rempah, lalu dipanggang. Setelah dipanggang, langsung dibaluri oleh saus mint yang banyak. Sehingga aroma ikannya cukup untuk memikat selera makan siapa saja.",
      "effect": "Memulihkan 9% Max HP dan 1.000 HP tambahan untuk Karakter yang dipilih."
    },
    "delicious": {
      "name": "Delicious Grilled Fish in Mint Sauce",
      "description": "Ikan panggang berbalut saus yang nikmat. Kulitnya yang renyah dan wangi, dagingnya yang empuk dan kenyal, cara memasak yang begitu bersahaja menghadirkan kelezatan yang luar biasa.",
      "effect": "Memulihkan 10% Max HP dan tambahan 1.200 HP untuk Karakter yang dipilih."
    }
  },
  "dishType": "Makanan Pemulihan",
  "version": "5.0"
}

=== dval-in/dvalin-data/data/KO/Food/SelvaSalad.json
{
  "id": "SelvaSalad",
  "name": "우림 샐러드",
  "description": "페이몬이 고심 끝에 개량한 아란나라의 샐러드. 하지만 수메르에는 이미 똑같은 레시피의 샐러드가 있었다. 뚠뚠 복숭아는 신선하고 아삭한 식감을 자랑하며 청량한 민트로 설탕의 달콤함을 대체했다. 풍미를 선사하기 위해 수메르 장미 액기스를 약간 넣었다. 미각과 후각을 동시에 사로잡는 상큼한 요리이다",
  "rarity": 2,
  "ingredients": [
    {
      "id": "ZaytunPeach",
      "name": "뚠뚠 복숭아",
      "amount": 2
    },
    {
      "id": "Mint",
      "name": "민트",
      "amount": 2
    },
    {
      "id": "SumeruRose",
      "name": "수메르 장미",
      "amount": 2
    },
    {
      "id": "ZaytunPeach",
      "name": "뚠뚠 복숭아",
      "amount": 2
    },
    {
      "id": "Mint",
      "name": "민트",
      "amount": 2
    },
    {
      "id": "SumeruRose",
      "name": "수메르 장미",
      "amount": 2
    }
  ],
  "dishType": "모험류 요리",
  "results": {
    "suspicious": {
      "name": "이상한 우림 샐러드",
      "description": "페이몬이 고심 끝에 개량한 아란나라의 샐러드. 하지만 수메르에는 이미 똑같은 레시피의 샐러드가 있었다. 뚠뚠 복숭아가 숙성을 넘어서 발효에 가까운 이상한 냄새를 풍기고 있으며 민트와 장미의 비율도 균형을 잃었다…",
      "effect": "파티 내 모든 캐릭터의 대시 시 소모하는 스태미나가 15% 감소한다. 지속 시간: 900초. 다인 모드 시 자신의 캐릭터에만 적용된다"
    },
    "normal": {
      "name": "우림 샐러드",
      "description": "페이몬이 고심 끝에 개량한 아란나라의 샐러드. 하지만 수메르에는 이미 똑같은 레시피의 샐러드가 있었다. 뚠뚠 복숭아는 신선하고 아삭한 식감을 자랑하며 청량한 민트로 설탕의 달콤함을 대체했다. 풍미를 선사하기 위해 수메르 장미 액기스를 약간 넣었다. 미각과 후각을 동시에 사로잡는 상큼한 요리이다",
      "effect": "파티 내 모든 캐릭터의 대시 시 소모하는 스태미나가 20% 감소한다. 지속 시간: 900초. 다인 모드 시 자신의 캐릭터에만 적용된다"
    },
    "delicious": {
      "name": "맛있는 우림 샐러드",
      "description": "페이몬이 고심 끝에 개량한 아란나라의 샐러드. 하지만 수메르에는 이미 똑같은 레시피의 샐러드가 있었다. 식자재로 선택한 뚠뚠 복숭아는 부드럽고 과즙이 가득하며 민트의 상큼함과 성숙한 장미에서 퍼지는 향기가 위장에 밀려 들어온다. 적당한 단맛과 시원함이 느껴진다. 이게 바로 「즐거운 맛」이 아닐까?",
      "effect": "파티 내 모든 캐릭터의 대시 시 소모하는 스태미나가 25% 감소한다. 지속 시간: 900초. 다인 모드 시 자신의 캐릭터에만 적용된다"
    }
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/TH/Food/Tulumba.json
{
  "id": "Tulumba",
  "name": "Tulumba",
  "description": "ของหวานที่ทำโดยการทอดน้ำมัน ใส่แป้งที่ปั้นไว้ลงไปในกระทะ แล้วทอดจนกลายเป็นสีเหลืองทอง จากนั้นจึงนำออกมาแช่ลงไปในน้ำเชื่อมขณะที่ยังร้อน ๆ อยู่ นี่คือความสุขที่ชาว Sumeru ขาดไม่ได้ในชีวิตประจำวัน",
  "rarity": 3,
  "ingredients": [
    {
      "id": "BirdEgg",
      "name": "Bird Egg",
      "amount": 3
    },
    {
      "id": "Flour",
      "name": "Flour",
      "amount": 2
    },
    {
      "id": "Sugar",
      "name": "Sugar",
      "amount": 2
    },
    {
      "id": "CoffeeBeans",
      "name": "Coffee Bean",
      "amount": 1
    },
    {
      "id": "BirdEgg",
      "name": "Bird Egg",
      "amount": 3
    },
    {
      "id": "Flour",
      "name": "Flour",
      "amount": 2
    },
    {
      "id": "Sugar",
      "name": "Sugar",
      "amount": 2
    },
    {
      "id": "CoffeeBeans",
      "name": "Coffee Bean",
      "amount": 1
    }
  ],
  "dishType": "เมนูการผจญภัย",
  "results": {
    "suspicious": {
      "name": "Tulumba รสประหลาด",
      "description": "ของหวานที่ทำโดยการทอดน้ำมัน ไม่ได้ถูกนำออกจากกระทะน้ำมันให้ทันเวลา ส่งผลให้เมื่อกินเข้าไปเพียงคำเดียว ทั้งปากก็เต็มไปด้วยความมันเลี่ยน จนต้องกระดกกาแฟเข้าไปหนึ่งแก้วเต็ม ๆ ถึงจะรอดพ้นจากความกระอักกระอ่วนมาได้",
      "effect": "ลดอัตราการเสียพลังกายจากการ ร่อนเวหาและการวิ่งให้กับ สมาชิกทั้งหมดในทีมลง 15% เป็นเวลา 900 วินาที เมื่อเล่นในโหมดเล่นหลายคน จะมีผลกับตัวละครของตัวเองเท่านั้น"
    },
    "normal": {
      "name": "Tulumba",
      "description": "ของหวานที่ทำโดยการทอดน้ำมัน ใส่แป้งที่ปั้นไว้ลงไปในกระทะ แล้วทอดจนกลายเป็นสีเหลืองทอง จากนั้นจึงนำออกมาแช่ลงไปในน้ำเชื่อมขณะที่ยังร้อน ๆ อยู่ นี่คือความสุขที่ชาว Sumeru ขาดไม่ได้ในชีวิตประจำวัน",
      "effect": "ลดอัตราการเสียพลังกายจากการ ร่อนเวหาและการวิ่งให้กับ สมาชิกทั้งหมดในทีมลง 20% เป็นเวลา 900 วินาที เมื่อเล่นในโหมดเล่นหลายคน จะมีผลกับตัวละครของตัวเองเท่านั้น"
    },
    "delicious": {
      "name": "Tulumba แสนอร่อย",
      "description": "ของหวานที่ทำโดยการทอดน้ำมัน ขนมสีทองอร่าม ถูกห่อด้วยไซรัปหวานละมุน หนึ่งคำต่อหนึ่งชิ้น เพียงชั่วพริบตาก็หมดเกลี้ยง อ๊ะ ดูเหมือนจะมีรอยน้ำเชื่อมหลงเหลืออยู่บนจานนะ บางทีอาจจะทำให้ความหวานอร่อยนี้ คงอยู่ต่อไปได้อีกสักชั่วครู่...?",
      "effect": "ลดอัตราการเสียพลังกายจากการ ร่อนเวหาและการวิ่งให้กับ สมาชิกทั้งหมดในทีมลง 25% เป็นเวลา 900 วินาที เมื่อเล่นในโหมดเล่นหลายคน จะมีผลกับตัวละครของตัวเองเท่านั้น"
    }
  },
  "version": "5.0"
}

=== dval-in/dvalin-data/data/PT/Food/CandiedAjilenakhNut.json
{
  "id": "CandiedAjilenakhNut",
  "name": "Doce de Mel com Tâmaras",
  "description": "Uma sobremesa suntuosa. Primeiro, a calda é fervida até ficar transparente, então é misturada com os recheios e a pasta de gergelim de Sumeru. Então, finalmente, a calda igualmente misturada é colocada em uma forma e descansa até atingir sua forma crocante. Dizem que as terras frias de Snezhnaya possuem um prato similar, com um perfil de sabor ligeiramente diferente. Claro, ambas as regiões naturalmente acreditam que a sua versão é a melhor de Teyvat.",
  "rarity": 3,
  "ingredients": [
    {
      "id": "AjilenakhNut",
      "name": "Tâmara",
      "amount": 4
    },
    {
      "id": "Almond",
      "name": "Amêndoa",
      "amount": 2
    },
    {
      "id": "Butter",
      "name": "Manteiga",
      "amount": 2
    },
    {
      "id": "SumeruRose",
      "name": "Rosa de Sumeru",
      "amount": 1
    },
    {
      "id": "AjilenakhNut",
      "name": "Tâmara",
      "amount": 4
    },
    {
      "id": "Almond",
      "name": "Amêndoa",
      "amount": 2
    },
    {
      "id": "Butter",
      "name": "Manteiga",
      "amount": 2
    },
    {
      "id": "SumeruRose",
      "name": "Rosa de Sumeru",
      "amount": 1
    }
  ],
  "dishType": "Pratos de DEF",
  "results": {
    "suspicious": {
      "name": "Doce de Mel com Tâmaras Estranho",
      "description": "Uma sobremesa rica. As nozes duras são como uma pedra escondida na areia, aguardando uma chance de atacarem. A doçura traz felicidade, mas a sensação dos pedaços duros nos dentes arruína ela.",
      "effect": "Aumenta a DEF de todos os membros da Equipe em 165 por 300s. No modo multijogador, terá efeito em si mesmo."
    },
    "normal": {
      "name": "Doce de Mel com Tâmaras",
      "description": "Uma sobremesa suntuosa. Primeiro, a calda é fervida até ficar transparente, então é misturada com os recheios e a pasta de gergelim de Sumeru. Então, finalmente, a calda igualmente misturada é colocada em uma forma e descansa até atingir sua forma crocante. Dizem que as terras frias de Snezhnaya possuem um prato similar, com um perfil de sabor ligeiramente diferente. Claro, ambas as regiões naturalmente acreditam que a sua versão é a melhor de Teyvat.",
      "effect": "Aumenta a DEF de todos os membros da Equipe em 200 por 300s. No modo multijogador, terá efeito em si mesmo."
    },
    "delicious": {
      "name": "Doce de Mel com Tâmaras Delicioso",
      "description": "Uma sobremesa rica. O mel derrete ao entrar em contato com a boca, revelando a castanha mergulhada em vermelho, cada camada levando a uma felicidade maior. Basta uma mordida para mergulhar numa banheira de doçura. Da próxima vez é melhor fazer mais!",
      "effect": "Aumenta a DEF de todos os membros da Equipe em 235 por 300s. No modo multijogador, terá efeito em si mesmo."
    },
    "special": {
      "id": "Halvamazd",
      "name": "Halvamazd",
      "description": "A especialidade da Nahida. Diz-se que Mazi significa \"sabedoria\" em Sumeru. Uma \"sabedoria\" assim requintada é realmente irresistível. Nahida exibia um sorriso suave no olhar: \"As anêmonas do mar ajudaram e testemunharam o crescimento dos peixes, então não é nada além do normal que os peixinhos quiseram dar algo em troca\".",
      "effect": "Aumenta a DEF de todos os membros da Equipe em 282 por 300s. No modo multijogador, terá efeito apenas em si mesmo.",
      "character": {
        "id": "Nahida",
        "name": "Nahida"
      }
    }
  },
  "version": "5.0"
}
