=== dval-in/dvalin-data/schemas/Ingredient.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Ingredients",
  "definitions": {
    "Ingredients": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "processing": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "amount": {
                "type": "number"
              }
            },
            "required": [
              "id",
              "name",
              "amount"
            ],
            "additionalProperties": false
          }
        },
        "recipes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name"
            ],
            "additionalProperties": false
          }
        },
        "source": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/EN/Ingredient/SpinelFruit.json
{
  "id": "SpinelFruit",
  "name": "Spinel Fruit",
  "description": "The crystalline trees that grow widely in areas with Liquid Phlogiston produce these gem-shaped fruits after absorbing phlogiston.",
  "recipes": [
    {
      "id": "GlitteringGemstones",
      "name": "Glittering Gemstones"
    }
  ],
  "source": [
    "Found in Liquid Phlogiston Zones"
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/TR/Ingredient/GlabrousBeans.json
{
  "id": "GlabrousBeans",
  "name": "Kabuksuz Nohut",
  "description": "Teyvat'ta yaygın olan hafif aromalı bir baklagildir. Çeşitli şekillerde hazırlanabilir ve bu nedenle dünyanın her yerindeki insanlar tarafından geniş çapta kabul görmektedir.",
  "recipes": [
    {
      "id": "MintyBeanSoup",
      "name": "Minty Bean Soup"
    },
    {
      "id": "Panipuri",
      "name": "Panipuri"
    },
    {
      "id": "AaruMixedRice",
      "name": "Aaru Mixed Rice"
    },
    {
      "id": "Fatteh",
      "name": "Fatteh"
    },
    {
      "id": "Cassoulet",
      "name": "Cassoulet"
    },
    {
      "id": "MintyBeanSoup",
      "name": "Naneli Fasulye Çorbası"
    },
    {
      "id": "Panipuri",
      "name": "Panipuri"
    },
    {
      "id": "AaruMixedRice",
      "name": "Karışık Aaru Pilavı"
    },
    {
      "id": "Fatteh",
      "name": "Nohutlu Fette"
    },
    {
      "id": "Cassoulet",
      "name": "Güveç"
    },
    {
      "id": "FriedShrimpBeanballs",
      "name": "Kızarmış Karidesli Nohut Köftesi"
    },
    {
      "id": "BlazedMeatStew",
      "name": "Yakıcı Et Yahnisi"
    }
  ],
  "source": [
    "ซื้อจากร้านขายอาหารใน Sumeru",
    "ซื้อจากร้านขายของชำใน Fontaine",
    "Sumeru'daki restoranlarda satılır.",
    "Fontaine'deki gıda pazarında satılır.",
    "Natlan'daki gıda pazarında satılır."
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/TH/Ingredient/BambooShoot.json
{
	"id": "BambooShoot",
	"name": "Bamboo Shoot",
	"description": "หน่ออ่อนของต้นไผ่ที่งอกขึ้นมาใหม่ ๆ นั้นมีกลิ่นหอมมาก มีเพียงที่ ๆ ต้นไผ่เจริญเติบโตได้เท่านั้นจึงจะมีวัตถุดิบทำอาหารที่แสนอร่อยนี้",
	"recipes": [
		{
			"id": "Wakatakeni",
			"name": "Wakatakeni"
		},
		{
			"id": "BambooShootSoup",
			"name": "Bamboo Shoot Soup"
		},
		{
			"id": "TriplelayeredConsomm",
			"name": "Triple-Layered Consommé"
		},
		{
			"id": "RightAtHome",
			"name": "Right at Home"
		},
		{
			"id": "BraisedMeatball",
			"name": "Braised Meatballs"
		},
		{
			"id": "TonkotsuRamen",
			"name": "Tonkotsu Ramen"
		},
		{
			"id": "OncidiumTofu",
			"name": "Oncidium Tofu"
		}
	],
	"source": [
		"พบได้ในโลกกว้าง",
		"คำแนะนำ: หาได้ที่ป่าไผ่ Qingce Village"
	],
	"version": "4.4"
}
