=== dval-in/dvalin-data/schemas/Ingredients.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "processing": {
      "items": {
        "properties": {
          "amount": {
            "type": "number"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "amount",
          "id",
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "recipes": {
      "items": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "description",
    "id",
    "name"
  ],
  "type": "object",
  "additionalProperties": false
}

=== dval-in/dvalin-data/data/FR/Ingredient/FermentedJuice.json
{
  "id": "FermentedJuice",
  "name": "Jus fermenté",
  "description": "Un jus fermenté au parfum fruité unique, souvent utilisé comme marinade.",
  "recipes": [
    {
      
      "id": "TripesDuPort",
      "name": "Tripes du port"
    },
    {
      
      "id": "VessieChicken",
      "name": "Poularde en vessie"
    }
  ],
  "source": [
    "Épiceries de Fontaine"
  ]
}
