=== dval-in/dvalin-data/schemas/JewelMaterial.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "convert": {
      "items": {
        "items": {
          "properties": {
            "amount": {
              "type": "number"
            },
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "amount",
            "id",
            "name"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "type": "array"
    },
    "craft": {
      "properties": {
        "cost": {
          "type": "number"
        },
        "items": {
          "items": {
            "properties": {
              "amount": {
                "type": "number"
              },
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "amount",
              "id",
              "name"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "cost",
        "items"
      ],
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "rarity": {
      "type": "number"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "description",
    "id",
    "name",
    "rarity",
    "source"
  ],
  "type": "object",
  "additionalProperties": false
}

=== dval-in/dvalin-data/data/FR/TalentLvlUpMaterial/DragonLordsCrown.json
{
	"id": "DragonLordsCrown",
	"name": "Couronne du roi-dragon",
	"description": "Infusé par les esprits et sculpté dans la roche, il est né au cœur de la montagne pour montrer la force de la terre face aux étendues de monolithes, et ses longues cornes dorées sont la marque de sa lutte contre un roi du passé.Cette corne avait, pendant un temps, été brisée et avait perdu de son éclat, mais désormais, elle brille d'une lueur froide et dorée, pendant que vous la tenez dans la paume de votre main.",
	"source": ["Défi d'Azhdaha (Niv.70+)"],
	"rarity": 5,
	"convert": [
		[
			{
				"id": "BloodjadeBranch",
				"name": "Branche de jade cramoisi",
				"amount": 1
			},
			{
				"id": "DreamSolvent",
				"name": "Solvant de rêve",
				"amount": 1
			}
		],
		[
			{
				"id": "GildedScale",
				"name": "Écaille dorée",
				"amount": 1
			},
			{
				"id": "DreamSolvent",
				"name": "Solvant de rêve",
				"amount": 1
			}
		]
	]
}

=== dval-in/dvalin-data/data/FR/JewelsMaterial/VayudaTurquoiseChunk.json
{
  "id": "VayudaTurquoiseChunk",
  "name": "Morceau de turquoise vayuda",
  "description": "« Le vent change toujours de direction. »<br/>« Un jour, il soufflera vers un meilleur avenir. »",
  "source": [
    "Butin d'Hypostase Anémo (Niv.60+)",
    "Butin de Wenut de Setekh (Niv.60+)",
    "Synthèse"
  ],
  "rarity": 4,
  "craft": {
    "cost": 900,
    "items": [
      {
        
        "id": "VayudaTurquoiseFragment",
        "name": "Fragment de turquoise vayuda",
        "amount": 3
      }
    ]
  },
  "convert": [
    [
      {
        
        "id": "AgnidusAgateChunk",
        "name": "Morceau d'agate agnidus",
        "amount": 1
      },
      {
        
        "id": "DustOfAzoth",
        "name": "Poudre d'Azoth",
        "amount": 9
      }
    ],
    [
      {
        
        "id": "VarunadaLazuriteChunk",
        "name": "Morceau de lazurite varunada",
        "amount": 1
      },
      {
        
        "id": "DustOfAzoth",
        "name": "Poudre d'Azoth",
        "amount": 9
      }
    ],
    [
      {
        
        "id": "NagadusEmeraldChunk",
        "name": "Morceau d'émeraude nagadus",
        "amount": 1
      },
      {
        
        "id": "DustOfAzoth",
        "name": "Poudre d'Azoth",
        "amount": 9
      }
    ],
    [
      {
        
        "id": "VajradaAmethystChunk",
        "name": "Morceau d'améthyste vajrada",
        "amount": 1
      },
      {
        
        "id": "DustOfAzoth",
        "name": "Poudre d'Azoth",
        "amount": 9
      }
    ],
    [
      {
        
        "id": "ShivadaJadeChunk",
        "name": "Morceau de jade shivada",
        "amount": 1
      },
      {
        
        "id": "DustOfAzoth",
        "name": "Poudre d'Azoth",
        "amount": 9
      }
    ],
    [
      {
        
        "id": "PrithivaTopazChunk",
        "name": "Morceau de topaze prithiva",
        "amount": 1
      },
      {
        
        "id": "DustOfAzoth",
        "name": "Poudre d'Azoth",
        "amount": 9
      }
    ]
  ]
}
