=== dval-in/dvalin-data/schemas/JewelsMaterial.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/JewelsMaterial",
  "definitions": {
    "JewelsMaterial": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "source": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "rarity": {
          "type": "number"
        },
        "craft": {
          "type": "object",
          "properties": {
            "cost": {
              "type": "number"
            },
            "items": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  }
                },
                "required": [
                  "id",
                  "name",
                  "amount"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "cost",
            "items"
          ],
          "additionalProperties": false
        },
        "convert": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "amount": {
                  "type": "number"
                }
              },
              "required": [
                "id",
                "name",
                "amount"
              ],
              "additionalProperties": false
            }
          }
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "source",
        "rarity"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/VI/JewelsMaterials/VarunadaLazuriteGemstone.json
{
	"id": "VarunadaLazuriteGemstone",
	"name": "Thanh Kim Sạch",
	"description": "\"Trong lý tưởng của ta không có chút vấy bẩn nào.\"<br/>\"Tôi phải đính chính với bạn, ở nơi này, người không phải gánh vác tội lỗi nào với Thần, chỉ có pháp luật và tòa án mới có thể luận tội.\"<br/>\"Họ thậm chí có thể luận tội cả tôi. Hãy tán dương sự tôn quý và thuần khiết của tôi đi.\"",
	"source": [
		"Ghép Nhận",
		"Xem Trang Thảo Phạt trong Bằng Chứng Mạo Hiểm"
	],
	"rarity": 5,
	"craft": {
		"cost": 2700,
		"items": [
			{
				"id": "VarunadaLazuriteChunk",
				"name": "Miếng Thanh Kim Sạch",
				"amount": 3
			}
		]
	},
	"convert": [
		{
			"0": {
				"id": "AgnidusAgateGemstone",
				"name": "Mã Não Cháy",
				"amount": 1
			},
			"1": {
				"id": "DustOfAzoth",
				"name": "Bụi Biến Đổi",
				"amount": 27
			}
		},
		{
			"0": {
				"id": "NagadusEmeraldGemstone",
				"name": "Ngọc Bích Sinh Trưởng",
				"amount": 1
			},
			"1": {
				"id": "DustOfAzoth",
				"name": "Bụi Biến Đổi",
				"amount": 27
			}
		},
		{
			"0": {
				"id": "VajradaAmethystGemstone",
				"name": "Tử Tinh Thắng Lợi",
				"amount": 1
			},
			"1": {
				"id": "DustOfAzoth",
				"name": "Bụi Biến Đổi",
				"amount": 27
			}
		},
		{
			"0": {
				"id": "VayudaTurquoiseGemstone",
				"name": "Tùng Thạch Tự Tại",
				"amount": 1
			},
			"1": {
				"id": "DustOfAzoth",
				"name": "Bụi Biến Đổi",
				"amount": 27
			}
		},
		{
			"0": {
				"id": "ShivadaJadeGemstone",
				"name": "Ngọc Băng",
				"amount": 1
			},
			"1": {
				"id": "DustOfAzoth",
				"name": "Bụi Biến Đổi",
				"amount": 27
			}
		},
		{
			"0": {
				"id": "PrithivaTopazGemstone",
				"name": "Hoàng Ngọc Cứng",
				"amount": 1
			},
			"1": {
				"id": "DustOfAzoth",
				"name": "Bụi Biến Đổi",
				"amount": 27
			}
		}
	],
	"version": "4.4"
}
