=== dval-in/dvalin-data/schemas/LocalMaterial.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "description",
    "id",
    "location",
    "name",
    "source",
    "version"
  ],
  "type": "object",
  "additionalProperties": false
}

=== dval-in/dvalin-data/data/IT/LocalMaterial/Cecilia.json
{
  "id": "Cecilia",
  "name": "Cecilia",
  "description": "Un fiore dall'aspetto incantevole che cresce solo nei luoghi dove soffiano i venti pi√π forti. Intangibile come il cuore puro di un'anima libera.",
  "source": [
    "Consiglio: si trova sul Promontorio Acchiappastelle",
    "Vai a raccogliere"
  ],
  "location": "Mondstadt",
  "version": "5.0"
}

=== dval-in/dvalin-data/data/TH/LocalMaterial/ClearwaterJade.json
{
  "id": "ClearwaterJade",
  "name": "Clearwater Jade",
  "description": "หยกที่เกิดบนหุบเขา Chenyu สัมผัสเย็นราวกับน้ำบริสุทธิ์ นั่นจึงเป็นที่มาของชื่อนี้",
  "source": [
    "พบได้ในโลกกว้าง",
    "คำแนะนำ: หาได้ที่บริเวณ Chenyu Vale: Southern Mountain",
    "พบได้ในโลกกว้าง",
    "คำแนะนำ: หาได้ที่บริเวณ Chenyu Vale: Southern Mountain",
    "ไปเก็บ"
  ],
  "location": "Liyue",
  "version": "4.4"
}

=== dval-in/dvalin-data/data/ES/LocalMaterial/Violetgrass.json
{
  "id": "Violetgrass",
  "name": "Campanita de cristal",
  "description": "Una pequeña flor con mucha vitalidad. Se dice que se abre hacia abajo para impedir que su fragancia se escape.",
  "source": [
    "Recolectar en peñascos de Liyue",
    "Recolectar"
  ],
  "location": "Liyue",
  "version": "5.0"
}

=== dval-in/dvalin-data/data/EN/LocalMaterial/SubdetectionUnit.json
{
  "id": "SubdetectionUnit",
  "name": "Subdetection Unit",
  "description": "Detection units produced by Fontaine Research Institute using new models of artificed components. Its original purpose was monitoring all kinds of environmental data.",
  "source": [
    "Found in the wild",
    "Recommendation:Found in Fontaine Research Institute of Kinetic Energy Engineering Region",
    "Recommendation: Found in Fontaine Research Institute of Kinetic Energy Engineering Region",
    "Go to collect"
  ],
  "location": "Fontaine",
  "version": "5.0"
}
