=== dval-in/dvalin-data/schemas/Potion.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Potion",
  "definitions": {
    "Potion": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "effect": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        },
        "craft": {
          "type": "object",
          "properties": {
            "cost": {
              "type": "number"
            },
            "items": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  }
                },
                "required": [
                  "id",
                  "name",
                  "amount"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "cost",
            "items"
          ],
          "additionalProperties": false
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "effect",
        "rarity",
        "craft"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/FR/Potion/HeatshieldPotion.json
{
  "id": "HeatshieldPotion",
  "name": "Potion de résistance Pyro",
  "description": "Une potion mystérieuse qui permet de résister aux environnements à haute température et augmente la RÉS Pyro. Son principe d'action consiste à adapter le corps à la chaleur plutôt que de le refroidir.",
  "effect": "Augmente la RÉS Pyro de tous les personnages de l'équipe de 25 % pendant 300 s.",
  "craft": {
    "cost": 100,
    "items": [
      {
        "id": "ButterflyWings",
        "name": "Ailes de papillon",
        "amount": 1
      },
      {
        "id": "FlamingFlowerStamen",
        "name": "Pistil de fleur enflammée",
        "amount": 1
      }
    ]
  },
  "rarity": 3,
  "version": "1.6"
}
