=== dval-in/dvalin-data/schemas/TalentLvlUpMaterial.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/TalentLvlUpMaterial",
  "definitions": {
    "TalentLvlUpMaterial": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "source": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "location": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        },
        "convert": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "amount": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "amount"
                  ],
                  "additionalProperties": false
                }
              }
            },
            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  }
                },
                "required": [
                  "id",
                  "name",
                  "amount"
                ],
                "additionalProperties": false
              }
            }
          ]
        },
        "craft": {
          "type": "object",
          "properties": {
            "cost": {
              "type": "number"
            },
            "items": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  }
                },
                "required": [
                  "id",
                  "name",
                  "amount"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "cost",
            "items"
          ],
          "additionalProperties": false
        },
        "domain": {
          "type": "string"
        },
        "days": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "source",
        "rarity",
        "version"
      ],
      "additionalProperties": false
    }
  }
}

=== dval-in/dvalin-data/data/ID/TalentLvlUpMaterial/GildedScale.json
{
  "id": "GildedScale",
  "name": "Gilded Scale",
  "description": "Setelah melewati waktu yang tak terhitung jumlahnya dan terurai ke dalam bumi, emas dan batu obsidian menyatu ke dalam darah dan daging mineral, dan dari situlah sisik-sisik zirah terbentuk.<br/>Rasa sakit yang membara, tangisan penuh derita yang tak bersuara... mungkin semua kesengsaraan itu akan menghilang di saat dendam kesumat yang memunculkan mereka, juga mencapai titik akhir.",
  "source": [
    "Hadiah tantangan Azhdaha Lv. 70+"
  ],
  "rarity": 5,
  "convert": [
    [
      {
        "id": "DragonLordsCrown",
        "name": "Dragon Lord's Crown",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Dream Solvent",
        "amount": 1
      }
    ],
    [
      {
        "id": "BloodjadeBranch",
        "name": "Bloodjade Branch",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Dream Solvent",
        "amount": 1
      }
    ]
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/ID/JewelsMaterial/VarunadaLazuriteGemstone.json
{
  "id": "VarunadaLazuriteGemstone",
  "name": "Varunada Lazurite Gemstone",
  "description": "\"Ideologiku tidak bernoda.\"\"Aku harus membenarkanmu. Orang-orang di sini tidak berdosa di mata para Dewa... hanya hukum dan Tribunal yang bisa menghakimi seseorang.\"\"Mereka bahkan dapat menghakimiku. Jadi pujalah keindahan dan kemurnianku.\"",
  "source": [
    "Didapatkan melalui Craft",
    "Buka Tab Investigasi di Buku Panduan Petualang"
  ],
  "rarity": 5,
  "craft": {
    "cost": 2700,
    "items": [
      {
        "id": "VarunadaLazuriteChunk",
        "name": "Varunada Lazurite Chunk",
        "amount": 3
      }
    ]
  },
  "convert": [
    [
      {
        "id": "AgnidusAgateGemstone",
        "name": "Agnidus Agate Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "NagadusEmeraldGemstone",
        "name": "Nagadus Emerald Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "VajradaAmethystGemstone",
        "name": "Vajrada Amethyst Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "VayudaTurquoiseGemstone",
        "name": "Vayuda Turquoise Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "ShivadaJadeGemstone",
        "name": "Shivada Jade Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "PrithivaTopazGemstone",
        "name": "Prithiva Topaz Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ]
  ],
  "version": "1.6"
}

=== dval-in/dvalin-data/data/PT/TalentLvlUpMaterial/HellfireButterfly.json
{
  "id": "HellfireButterfly",
  "name": "Borboleta das Chamas Infernais",
  "description": "O selo de gelo foi quebrado sob a pressão, e a medida que a sua determinação antiga saiu de sua prisão branca pálida e ela lembrou seu antigo nome mais uma vez, e a borboleta imortal dançou entre a carne e sangue flamejantes. E então ela lembrou seu passado, vagando pela terra, queimando todo o mal, assim como o rosto da pessoa que ela não poderia ver novamente.",
  "source": [
    "Recompensa do Desafio de Signora Nv.70+",
    "Recompensa do Desafio de Signora Nv.70+"
  ],
  "rarity": 5,
  "convert": [
    [
      {
        "id": "MoltenMoment",
        "name": "Momento Derretido",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Solvente dos Sonhos",
        "amount": 1
      }
    ],
    [
      {
        "id": "AshenHeart",
        "name": "Coração das Cinzas",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Solvente dos Sonhos",
        "amount": 1
      }
    ],
    [
      {
        "id": "MoltenMoment",
        "name": "Momento Derretido",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Solvente dos Sonhos",
        "amount": 1
      }
    ],
    [
      {
        "id": "AshenHeart",
        "name": "Coração das Cinzas",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Solvente dos Sonhos",
        "amount": 1
      }
    ]
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/RU/TalentLvlUpMaterial/LightlessMass.json
{
  "id": "LightlessMass",
  "name": "Тёмная масса",
  "description": "Вселенная - темное и холодное место. Но приглядитесь хорошенько. Внутри всегда есть слабые отблески света, как жемчужины, сверкающие в песке, как осколки алмаза, рассыпанные по асфальту, как огни, пробивающиеся сквозь туманную ночь, как искры, зажигающие самые яркие огни.",
  "source": [
    "Всепожирающий нарвал Ур. 70+",
    "Всепожирающий нарвал Ур. 70+"
  ],
  "rarity": 5,
  "convert": [
    [
      {
        "id": "LightlessSilkString",
        "name": "Тёмная шёлковая нить",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Растворитель снов",
        "amount": 1
      }
    ],
    [
      {
        "id": "LightlessEyeOfTheMaelstrom",
        "name": "Тёмный глаз вихря",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Растворитель снов",
        "amount": 1
      }
    ],
    [
      {
        "id": "LightlessSilkString",
        "name": "Тёмная шёлковая нить",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Растворитель снов",
        "amount": 1
      }
    ],
    [
      {
        "id": "LightlessEyeOfTheMaelstrom",
        "name": "Тёмный глаз вихря",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Растворитель снов",
        "amount": 1
      }
    ]
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/FR/TalentLvlUpMaterial/AshenHeart.json
{
  "id": "AshenHeart",
  "name": "Cœur de cendre",
  "description": "Les larmes ne peuvent éteindre les flammes. Tristesse et rage, aussi brûlantes que la fonte, coulent dans ses veines et s'évacuent par ses glandes lacrymales.<br/>Le premier Fatui l'a découverte avant que son cœur ne soit détruit par les flammes éternelles. Il fit d'elle une alliée, car il avait compris que seules une haine et une obstination plus féroces pouvaient éteindre le feu qui la dévorait.",
  "source": [
    "Défi de Signora (Niv.70+)"
  ],
  "rarity": 5,
  "convert": [
    [
      {
        "id": "MoltenMoment",
        "name": "Moment en fusion",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Solvant de rêve",
        "amount": 1
      }
    ],
    [
      {
        "id": "HellfireButterfly",
        "name": "Papillon infernal",
        "amount": 1
      },
      {
        "id": "DreamSolvent",
        "name": "Solvant de rêve",
        "amount": 1
      }
    ]
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/TH/JewelsMaterial/PrithivaTopazGemstone.json
{
  "id": "PrithivaTopazGemstone",
  "name": "Prithiva Topaz Gemstone",
  "description": "เงินทั้งหมดที่หมุนเวียนอยู่ในแผ่นดินใหญ่คือเนื้อและเลือดของฉัน<br/>\"ด้วยวิธีนี้ฉันเป็นผู้รับประกันหยาดเหงื่อ ปัญญา และอนาคตของมนุษยชาติทั้งหมด\"<br/>\"นี่คือความเชื่อของฉันที่มีต่อสิ่งมีชีวิต การทรยศต่อมันจะทำให้เลือดของฉันต้องแปดเปื้อน\"",
  "source": [
    "ได้รับจากการสรรสร้าง",
    "ดูที่แท็บปราบปรามในคู่มือนักผจญภัย"
  ],
  "rarity": 5,
  "craft": {
    "cost": 2700,
    "items": [
      {
        "id": "PrithivaTopazChunk",
        "name": "Prithiva Topaz Chunk",
        "amount": 3
      }
    ]
  },
  "convert": [
    [
      {
        "id": "AgnidusAgateGemstone",
        "name": "Agnidus Agate Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "VarunadaLazuriteGemstone",
        "name": "Varunada Lazurite Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "NagadusEmeraldGemstone",
        "name": "Nagadus Emerald Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "VajradaAmethystGemstone",
        "name": "Vajrada Amethyst Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "VayudaTurquoiseGemstone",
        "name": "Vayuda Turquoise Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ],
    [
      {
        "id": "ShivadaJadeGemstone",
        "name": "Shivada Jade Gemstone",
        "amount": 1
      },
      {
        "id": "DustOfAzoth",
        "name": "Dust of Azoth",
        "amount": 27
      }
    ]
  ],
  "version": "5.0"
}
