=== dval-in/dvalin-data/schemas/WeaponPrimaryMaterial.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"craft": {
			"properties": {
				"cost": {
					"type": "number"
				},
				"items": {
					"items": {
						"properties": {
							"amount": {
								"type": "number"
							},
							"id": {
								"type": "string"
							},
							"name": {
								"type": "string"
							}
						},
						"required": ["amount", "id", "name"],
						"type": "object"
					},
					"type": "array"
				}
			},
			"required": ["cost", "items"],
			"type": "object"
		},
		"days": {
			"items": {
				"type": "string"
			},
			"type": "array"
		},
		"description": {
			"type": "string"
		},
		"domain": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"location": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"rarity": {
			"type": "number"
		},
		"source": {
			"items": {
				"type": "string"
			},
			"type": "array"
		},
		"version": {
			"type": "string"
		}
	},
	"required": [
		"days",
		"description",
		"domain",
		"id",
		"location",
		"name",
		"rarity",
		"source",
		"version"
	],
	"type": "object",
	"additionalProperties": false
}

=== dval-in/dvalin-data/data/IT/TalentLvlUpMaterial/TeachingsOfEquity.json
{
  "id": "TeachingsOfEquity",
  "name": "Insegnamenti di equità",
  "description": "L'equità è il confine della Nazione dell'Acqua. L'equità pone limiti ai diritti. Senza equità, i diritti concessi dalla legge verrebbero abusati e diventerebbero uno strumento per danneggiare le nostre virtuose tradizioni.",
  "source": [
    "Si acquista nel Negozio di regali"
  ],
  "location": "Mondstadt",
  "rarity": 2,
  "domain": "Tenue gloria dimenticata",
  "days": [
    "Lunedì",
    "Giovedì",
    "Domenica"
  ],
  "version": "4.0"
}

=== dval-in/dvalin-data/data/RU/WeaponPrimaryMaterial/SilverGobletOfThePristineSea.json
{
  "id": "SilverGobletOfThePristineSea",
  "name": "Серебряный кубок непорочного моря",
  "description": "Во времена, когда золотой саван покрывал землю, чистую родниковую воду приходилось прятать в потаённых горных ручьях. В этих святилищах и рождались Рыцари чистых родников. Рыцари поклялись серебряными доспехами защищать духов, рождённых из чистой воды, защищать своих собратьев, которые тоже хранят веру в единую истинную купель, противостоящую вездесущей золотой силе, запятнавшей небо и затмившей солнце. Но это лишь древняя легенда... Вскоре после того, как империя рухнула и канула в Лету, рыцари, противостоявшие тирану, сбросили свои доспехи, а их истории были запрятаны в запутанной паутине сказаний и баллад.",
  "source": [
    "Алхимия"
  ],
  "location": "Фонтейн",
  "rarity": 4,
  "craft": {
    "cost": 350,
    "items": [
      {
        "id": "WineGobletOfThePristineSea",
        "name": "Чаша непорочного моря",
        "amount": 3
      }
    ]
  },
  "domain": "Эхо глубоких приливов",
  "days": [
    "Среда",
    "Суббота",
    "Воскресенье"
  ],
  "version": "4.0"
}

=== dval-in/dvalin-data/data/RU/TalentLvlUpMaterial/TeachingsOfProsperity.json
{
  "id": "TeachingsOfProsperity",
  "name": "Учения о «Процветании»",
  "description": "Процветание - это стремление царства земли. Процветание - это благословение Ли Юэ, великого города, основанного богами и людьми, это источник мира на земле.",
  "source": [
    "Сувенирная лавка"
  ],
  "location": "Мондштадт",
  "rarity": 2,
  "domain": "Тайшаньфу",
  "days": [
    "Понедельник",
    "Четверг",
    "Воскресенье",
    "Понедельник",
    "Четверг",
    "Воскресенье"
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/TH/WeaponPrimaryMaterial/FragmentOfDecarabiansEpic.json
{
  "id": "FragmentOfDecarabiansEpic",
  "name": "Fragment of Decarabian's Epic",
  "description": "Andrius นั้นครั้งหนึ่งเคยประกาศสงครามกับ Hightower Uniking แต่ก็ไม่สามารถทำอะไรได้แม้แต่จะสร้างความเสียหายให้แก่เมือง ถ้าไม่ใช่เพราะเพื่อบทเพลงแห่งอิสรภาพที่ทำให้เมืองแตกออกเป็นเสี่ยง ๆ แล้วล่ะก็ ฝันนี้ก็จะคงอยู่ไปตลอดกาล",
  "source": [
    "ได้รับจากการสรรสร้าง"
  ],
  "location": "Mondstadt",
  "rarity": 4,
  "craft": {
    "cost": 350,
    "items": [
      {
        "id": "DebrisOfDecarabiansCity",
        "name": "Debris of Decarabian's City",
        "amount": 3
      }
    ]
  },
  "domain": "สวนดอก Cecilia",
  "days": [
    "วันจันทร์",
    "วันพฤหัสบดี",
    "วันอาทิตย์"
  ],
  "version": "1.6"
}

=== dval-in/dvalin-data/data/TR/WeaponPrimaryMaterial/BrokenGobletOfThePristineSea.json
{
  "id": "BrokenGobletOfThePristineSea",
  "name": "Saf Denizin Kırık Kadehi",
  "description": "Efsanelere göre İlk Taht Hırsızı Ezeli Deniz'e geldiğinde ilk Hükümdar ona bir kupa su verdi. Daha sonra o mutlak Tanrı Kral haline geldi, bu suyu gizemli çiy damlacıklarını arıtmak için kullandı ve bu sayede muhteşem ve güçlü bir imparatorluk oluşturdu. Fakat bu artık kadim bir hikayeden ibaret ve karakterler derin sularda yaşayan balık sürülerinin saçtığı ışıkların arasında uyumakta.",
  "source": [
    "Hediye Dükkanında takas edilir."
  ],
  "location": "Fontaine",
  "rarity": 2,
  "domain": "Derin Dalgaların Yankıları",
  "days": [
    "Çarşamba",
    "Cumartesi",
    "Pazar"
  ],
  "version": "4.0"
}

=== dval-in/dvalin-data/data/EN/TalentLvlUpMaterial/PhilosophiesOfElegance.json
{
  "id": "PhilosophiesOfElegance",
  "name": "Philosophies of Elegance",
  "description": "Elegance is the form of the nation of thunder.<br/>Elegance abhors vulgarity, and the elegant ever walk alone. Resisting base evils, unmoved by base loves, never taking refuge in base ignorance â€” that is how one perceives the chasm between the elegant and the contemptuous.",
  "source": [
    "Crafted"
  ],
  "location": "Inazuma",
  "rarity": 4,
  "craft": {
    "cost": 550,
    "items": [
      {
        "id": "GuideToElegance",
        "name": "Guide to Elegance",
        "amount": 3
      }
    ]
  },
  "domain": "Violet Court",
  "days": [
    "Tuesday",
    "Friday",
    "Sunday"
  ],
  "version": "5.0"
}

=== dval-in/dvalin-data/data/EN/TalentLvlUpMaterial/GuideToAdmonition.json
{
  "id": "GuideToAdmonition",
  "name": "Guide to Admonition",
  "description": "Admonition is the branches of the nation of wisdom. Admonition is paired with wise thinking. Careful deliberation affords humble words a clarity that convinces the wise and enlightens the foolish. Such words allow wisdom to flow like an unobstructed river.",
  "source": [
    "Crafted"
  ],
  "location": "Sumeru",
  "rarity": 3,
  "craft": {
    "cost": 175,
    "items": [
      {
        "id": "TeachingsOfAdmonition",
        "name": "Teachings of Admonition",
        "amount": 3
      }
    ]
  },
  "domain": "Steeple of Ignorance",
  "days": [
    "Monday",
    "Thursday",
    "Sunday"
  ],
  "version": "3.0"
}
